---

name: Action self-test

on:
  issues:
    types: [ opened, edited, closed, reopened, assigned ]

jobs:
  test-action:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test the action locally
        uses: ./
        with:
          gitub_token: ${{ secrets.GITHUB_TOKEN_2 }}
          github_project_title: Main Backlog
          github_org: launchgood
