---

name: Action self-test

on:
  pull_request:
    branches: [ '*' ]

jobs:
  test-action:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test the action locally
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
